language: ruby
rvm:
    - 2.7.1
cache: bundler
services:
    - postgresql
before_script:
    - bundle exec rails db:create
    - bundle exec rails db:migrate
    - bundle exec rails db:seed
script: bundle exec rspec spec