addons: 
  code_climate: 
    repo_token: cbdbd21b87fb7b4ec3ff5e4d47544cf3d5d47d88285573e03650fb9fbea0e30f
    postgresql: "9.4"
services: 
  - postgres
after_success: 
  - "bundle exec codeclimate-test-reporter"
before_script: 
  - "cp config/database.yml.travis config/database.yml"
  - "psql -c 'create database bank_account_test;' -U postgres"
dist: trusty
language: ruby
rvm: 
  - "2.7.1"
script: 
	- "RAILS_ENV=test bundle exec rake db:schema:load --trace"
	- "bundle exec rake db:test:prepare"
  - "bundle exec rake rspec spec/"
services: 
  - redis-server