language: ruby
rvm:
    - 2.7.1
env:
    - RAILS_ENV='test'
cache: bundler
services:
    - postgresql
before_script:
    - bundle exec rails db:create db:migrate db:seed --trace
script: bundle exec rspec spec