version: '3'

volumes:
    redis:
    db:
services:
    db:
        image: 'postgres:9.6-alpine'
        hostname: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'magnetis'
        ports:
            - '5432:5432'
        volumes:
            - 'db:/var/lib/postgresql/data'
    redis:
        image: 'redis:4.0-alpine'
        hostname: redis
        container_name: redis
        command: 'redis-server --requirepass magnetis'
        sysctls:
            net.core.somaxconn: 1024
        ports:
            - '6379:6379'
        volumes:
            - 'redis:/data'
    web:
        depends_on:
            - 'db'
            - 'redis'
        image: 'apsferreira/bank-account:latest'
        container_name: bank-account
        hostname: bank_account
        restart: always
        command: /bin/bash -c "bundle exec rails db:drop db:create db:migrate db:seed && bundle exec rails s -b 0.0.0.0"
        volumes:
            - '.:/app'
        ports:
            - "3000:3000"
        env_file:
            - '.env'
        stdin_open: true
        tty: true
    sidekiq:
        depends_on:
            - 'web'
        image: 'apsferreira/bank-account:latest'
        container_name: sidekiq
        command: 'bundle exec sidekiq -C config/sidekiq.yml.erb'
        volumes:
            - '.:/app'
        env_file:
            - '.env'
          