# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: UTF8
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  timeout: 5000
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } * Integer(ENV.fetch("WEB_CONCURRENCY") { 2 }) %>

development:
  <<: *default
  database: <%= "#{ENV["DB_NAME"]}_development" %>

test:
  <<: *default
  database: <%= "#{ENV["DB_NAME"]}_test" %>

staging:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
